[".hammerspoon/stackline"]
  type = "git-repo"
  url = "https://github.com/AdamWagner/stackline.git"
  refreshPeriod = "168h"
[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm.git"
  refreshPeriod = "168h"
[".zinit/bin"]
  type = "git-repo"
  url = "https://github.com/z-shell/zi"
  refreshPeriod = "168h"
[".zinit/emacs-vterm-zsh.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/akermu/emacs-libvterm/master/etc/emacs-vterm-zsh.sh"
  refreshPeriod = "168h"
