{{ if eq .chezmoi.os "darwin" -}}
[".hammerspoon/stackline"]
  type = "git-repo"
  url = "https://github.com/AdamWagner/stackline"
  refreshPeriod = "168h"
{{- end }}
[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"
[".zinit/bin"]
  type = "git-repo"
  url = "https://github.com/zdharma-continuum/zinit"
  refreshPeriod = "168h"
